noranekoproject/noraneko/urls.py
from django.urls import path
from .views import NekoPostListView,NekoPostDetailView,PostCommentCreateView,ReplyCommentView


urlpatterns = [
    path('post_list/',NekoPostListView.as_view(), name='post_list'),
    path('post_list/<int:pk>/',NekoPostDetailView.as_view(), name='post_detail'),
    path('comment_create/<int:pk>',PostCommentCreateView.as_view(), name='comment_create'),
    path('reply_comment/<int:pk>', ReplyCommentView.as_view(), name='reply_comment'),
]

noranekoproject/noranekoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noraneko.urls')),
]

noranekoproject/noraneko/models.py
from django.db import models
from django.utils import timezone

# 参考サイト：https://blog.narito.ninja/detail/173/


class NekoPost (models.Model):
    """掲示板に投稿する内容"""
    name = models.CharField('名前', max_length=255, default='名無し')
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title


class PostComment(models.Model):
    """投稿に紐づくコメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(
        NekoPost, on_delete=models.CASCADE, verbose_name='対象投稿')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]


class ReplyComment(models.Model):
    """コメントに紐づく返信"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(
        PostComment, on_delete=models.CASCADE, verbose_name='対象コメント')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.text[:20]

noranekoproject/noraneko/forms.py
from django import forms
from noraneko.models import PostComment, ReplyComment


class CommentCreateForm(forms.ModelForm):
    """コメント投稿フォーム"""

    class Meta:
        model = PostComment
        # データとしては必要だがユーザが入力してほしくないところ
        exclude = ('target', 'created_at')
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'placeholder': 'コメントを入力して下さい。'}
            )
        }

class ReplyCreateForm(forms.ModelForm):
    """コメントに対する返信フォーム"""

    class Meta:
        model = ReplyComment
        exclude = ('target','created_at')

noranekoproject/noraneko/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import NekoPost,PostComment,ReplyComment
from django.views import generic
from noraneko.forms import CommentCreateForm, ReplyCreateForm


# Create your views here.
def indexfunc(repuest):
  return render(repuest,'index')

class NekoPostListView(generic.ListView):
  model = NekoPost
 

class NekoPostDetailView(generic.DetailView):
  model = NekoPost
  

class PostCommentCreateView(generic.CreateView):
  model = PostComment
  form_class = CommentCreateForm

  def form_valid(self,form):
    nekopost = get_object_or_404(NekoPost, pk=self.kwargs['pk'])
    comment = form.save(commit=False)
    comment.target = nekopost
    comment.save()
    return redirect('post_detail',pk=self.kwargs['pk'])
  
  def get_context_data(self,**kwargs):
    context = super().get_context_data(**kwargs)
    context['nekopost'] = get_object_or_404(NekoPost,pk=self.kwargs['pk'])
    return context

    
class ReplyCommentView(generic.CreateView):
  model = ReplyComment
  form_class = ReplyCreateForm
  
  def form_valid(self,form):
    comment_pk = self.kwargs['pk']
    comment = get_object_or_404(PostComment,pk=comment_pk)
    reply = form.save(commit=False)
    reply.target = comment
    reply.save()
    return redirect('post_detail',pk=comment.target.pk)

  def get_context_data(self,**kwargs):
    context = super().get_context_data(**kwargs)
    comment = get_object_or_404(PostComment,pk=self.kwargs['pk'])
    context['post'] = comment.target
    return context
 

noranekoproject/templates/base.html
<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block customcss %}
    {% endblock customcss %}

    <title>保護ねこを家族にする</title>
</head>

<body>
    {% block header %}
    {% endblock header %}
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

noranekoproject/templates/create_chat.html
{% extends 'base.html' %}
{% block customcss%}
{% endblock customcss%}

{% block content %}
<form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="field">
          {{ field.label_tag }}
          {{ field }}
          {% if field.help_text %}
            <span class="helptext">※{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}

        <button type="submit" class="btn-link">送信</button>
        <a class="button btn-link" href="{% url 'list_chat' %}">戻る</a>
    </form>
      
{% endblock content %}

noranekoproject/templates/detail_chat.html
{% extends 'base.html' %}

{% block customcss%}
{% endblock customcss%}

{% block header%}
<div class="alert alert-warning" role="alert">相談・雑談</div>


{% endblock header%}

{% block content%}
<div class='container'>
  <div class="alert alert-success" role="alert">
    <p>タイトル：{{ object.title }}</p>
    <p>コメント：{{ object.content }}</p>
  </div>
  <a href="{% url 'create_chat' comment.pk %}" target="_blank" rel="nofollow">返信する</a>
  <a href="{% url 'good' object.pk %}" class="btn btn-primary " role="button" aria-pressed="true">いいね</a>
</div>
{% endblock content%}

noranekoproject/templates/list_chat.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<div class="alert alert-warning" role="alert">相談・雑談</div>
<p>気になるタイトルをのぞいてみよう！</p>
{% endblock header %}

{% block content %}
<div class='container'>
  {% for item in object_list %}
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">
        <a href="{% url 'detail_chat' item.pk %}">{{ item.title }}</a>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="card-link">Card link</a>
      <a href="#" class="card-link">Another link</a>
    </div>
  </div>
  {% comment %} <div class="card">
    <div class="card-body">
      <p>タイトル<a href="{% url 'detail_chat' item.pk %}">{{ item.title }}</a></p>
    </div>
  </div> {% endcomment %}
  {% endfor%}
  {% comment %} {% endfor %}   {% endcomment %}
</div>
{% endblock content %}

noranekoproject/templates/noraneko/nekopost_detail.html
{% extends '../base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<div class="alert alert-warning" role="alert">投稿詳細</div>
{% endblock header %}

{% block content %}
<div class='container'>
    <div class="card" style="width: 18rem;">
        <h3>{{nekopost.title}}</h3>
        <p>{{nekopost.content}}</p>
    </div>
</div>
<section id="comment">
    <h2 class="section-title">Comment</h2>
    <p><a href="{% url 'comment_create' nekopost.id %}" target="_blank" rel="nofollow">記事にコメントする</a></p>
    <!-- コメント一覧 -->
    {% for comment in nekopost.postcomment_set.all %}
    <div class="comment">
        <h3>{{ comment.name }}</h3>
        <time class="updated_at" datetime="{{ comment.created_at | date:'Y-m-d' }}">{{ comment.created_at}}</time>
        <div class="description markdown-body">
            {{ comment.text }}
        </div>
        <p>
            <a href="{% url 'reply_comment' comment.id %}" target="_blank" rel="nofollow">返信する</a>
        </p>
    </div>
        <!-- リプライ一覧 -->
        {% for reply in comment.replycomment_set.all %}
        <div class="reply">
            <p>{{ reply.name }}</p>
            <time class="updated_at" datetime="{{ reply.created_at | date:'Y-m-d' }}">{{ reply.created_at}}</time>
            <div class="description markdown-body">
                {{ reply.text }}
            </div>
        </div>
        {% endfor %}
        <!-- リプライ一覧終わり -->
    {% empty %}
    <p>まだコメントはありません。</p>
    {% endfor %}
    <!-- コメント一覧終わり -->
</section>

{% endblock content %}

noranekoproject/templates/noraneko/nekopost_list.html
{% extends '../base.html' %}

{% block customcss %}
{% endblock customcss %}

{% block header %}
<div class="alert alert-warning" role="alert">相談・雑談</div>
{% endblock header %}

{% block content %}
<div class='container'>
    {% for item in object_list %}
    <a href="{% url 'post_detail' item.pk %}">
        <div class="card" style="width: 18rem;">
            <h3>{{item.title}}</h3>
            <p>{{item.content}}</p>
        </div>
    </a>
    {% empty %}
    <p class="post">まだ記事がありません。</p>
    {% endfor%}
</div>
{% endblock content %}

noranekoproject/templates/noraneko/postcomment_form.html
{% extends '../base.html' %}

{% block content %}
<form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="field">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
        <span class="helptext">※{{ field.help_text }}</span>
        {% endif %}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}

    <button type="submit" class="btn-link">送信</button>
    <a class="button btn-link" href="{% url 'post_detail' nekopost.pk %}">送信せずに戻る</a>
</form>

{% endblock %}

noranekoproject/templates/noraneko/replycomment_form.html
{% extends '../base.html' %}

{% block content %}
<form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="field">
        {{ field.label_tag }}
        {{ field }}
        {% if field.help_text %}
        <span class="helptext">※{{ field.help_text }}</span>
        {% endif %}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}

    <button type="submit" class="btn-link">送信</button>
    
</form>

{% endblock %}

noranekoproject/templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
{% comment %} <form action='' method='POST' enctype="multipart/form-data">{% csrf_token %}
<p>タイトル：<input type='text' name='title'></p>
<p>コメント：<input type='text' name='content'></p>
<input type='submit' value='投稿'> {% endcomment %}
{% comment %} </form> {% endcomment %}
<form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="field">
          {{ field.label_tag }}
          {{ field }}
          {% if field.help_text %}
            <span class="helptext">※{{ field.help_text }}</span>
          {% endif %}
          {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}

        <button type="submit" class="btn-link">送信</button>
        <a class="button btn-link" href="{% url 'detail_chat' %}"target="_blank" rel="nofollow">返信する</a>
    </form>
      
{% endblock content %}